pipeline {
    agent { any }

    environment{
        NAME = "Cyrus"
    }

    stages{

        stage("Coucou") {

            steps{
                echo 'Coucou, $(env.NAME)'
            }






        }



    }




}